### ISSUE TITLE
绑定None键时于媒体控制键冲突

### ISSUE THREAD

**Issue by FallenCrystal** [K-o-d-y/Debug-Issues#10]
假如我使用了.bind aura none 那么在使用媒体键控制系统时会开启aura
这个是可以叠加的 有什么功能绑定就在控制媒体键时全部切换状态
Debug v4.9

**Comment by FallenCrystal** [comment]
在config里把bindkey调为0即可

**Comment by K-o-d-y** [comment]
新版本已修复此问题

**Comment by K-o-d-y** [comment]
![image](https://user-images.githubusercontent.com/45705915/114886830-78635680-9e3a-11eb-87f6-9b1551f01914.png)
