### ISSUE TITLE
HitBox

### ISSUE THREAD

**Issue by heckerpowered** [K-o-d-y/Debug-Issues#21]
HitBox开启时不影响方块交互

**Comment by K-o-d-y** [comment]
具体是怎么影响

**Comment by heckerpowered** [comment]
很难描述,比如说有一个玩家在旁边,我鼠标中心是方块,但是由于HitBox变大了没法打中方块。我想让HitBox开启时不仅能命中被变大后的HitBox挡住的方块，并且还能命中玩家

**Comment by smallshen** [comment]
用onhold
